### ISSUE TITLE
subtree: Need a tutorial for new layer

### ISSUE THREAD

**Issue by mine260309** [openbmc/docs#42]
The subtree doc is great and introduce the develop flow on existing openbmc.

But I do not know how to add a new layer to the combo, e.g. if a (new) system vendor foo adds a new machine bar.
To do it right with openbmc's subtree:
1. They will have their own repo `meta-foo` with machine layer `meta-bar`.
2. They need to know how to correctly add this subtree into openbmc

This issue is to ask for an introduction about the above 2, so system vendors know how to do it correctly based on openbmc's subtree work flow.

**Comment by geissonator** [comment]
FYI @dcobbley

**Comment by WangKaiwh** [comment]
@mine260309 您好，对于厂商没有提供meta-foo(yocto方式构建)的方案，需要怎么做？ 个人可以移植吗 ？

**Comment by WangKaiwh** [comment]
@geissonator How to add a new meta-foo with new cpu ? Thx.

**Comment by mine260309** [comment]
@WangKaiwh Please use English so that all the community could read the comments.

As far as I know, when a new layer is added, Brad takes care of the subtree. Hopefully @bradbishop could share some information about this.

**Comment by williamspatrick** [comment]
We no longer use subtrees.
