### ISSUE TITLE
How to add a new recipe into OpenBMC 

### ISSUE THREAD

**Issue by brendenlai** [openbmc/docs#44]

**Comment by brendenlai** [comment]
How to write a  recipe for adding features  into OpenBMC image?
I just try to add ipmitool(dbus version) into romulus image . 
But i don't know how to write the bb files , can someone write a tutorial about this subject ?

**Comment by bradbishop** [comment]
> How to write a  recipe for adding features  into OpenBMC image?

For general recipe writing overview this is a helpful page:

https://www.yoctoproject.org/docs/current/dev-manual/dev-manual.html#new-recipe-writing-a-new-recipe

> I just try to add ipmitool(dbus version) into romulus image . 

One quick way to do this is just add a line like

```IMAGE_INSTALL_append = " ipmitool"```

to your build/local.conf.  Note the space between the quote and the
ipmitool - it is required.

> But i don't know how to write the bb files , can someone write a tutorial about this subject ?

**Comment by brendenlai** [comment]
> One quick way to do this is just add a line like
> 
> IMAGE_INSTALL_append = " ipmitool"
> 
> to your build/local.conf.  Note the space between the quote and the
> ipmitool - it is required.
Where do i put ipmitool ? the same folder as local.conf ?
if it works , where ipmitool located in image tree ?

**Comment by brendenlai** [comment]
> How to write a recipe for adding features into OpenBMC image?
> For general recipe writing overview this is a helpful page: https://www.yoctoproject.org/docs/current/dev-manual/dev-manual.html#new-recipe-writing-a-new-recipe
> I just try to add ipmitool(dbus version) into romulus image .
> One quick way to do this is just add a line like IMAGE_INSTALL_append = " ipmitool" to your build/local.conf. Note the space between the quote and the ipmitool - it is required.
> […](#)
> But i don't know how to write the bb files , can someone write a tutorial about this subject ?

**Comment by bradbishop** [comment]
On Wed, Jan 30, 2019 at 03:00:33PM +0000, brendenlai wrote:
> > One quick way to do this is just add a line like
> > 
> > IMAGE_INSTALL_append = " ipmitool"
> > 
> > to your build/local.conf.  Note the space between the quote and the
> > ipmitool - it is required.
> Where do i put ipmitool ? the same folder as local.conf ?
You put the IMAGE_INSTALL_append line right in local.conf.

> if it works , where ipmitool located in image tree ? 
/usr/bin/ipmitool
