### ISSUE TITLE
Document accessible markup patterns for icon use

### ISSUE THREAD

**Issue by derick-montague** [openbmc/docs#45]

**Comment by gtmills** [comment]
@derick-montague Can you add a description? Should this go in the webui repo instead?

**Comment by derick-montague** [comment]
@gtmills I will update the description. I was making this to address some of our conversation in the mail list. Should this type of documentation be done in the webui repo or is it actual documentation?

@edtanous:
> My take on this is that we should do whatever is easiest to maintain.
Today we use both custom SVGs inline in the nav bar, as well as some
font icons from the glyficons pack.  There were some concerns about
accessibility on font icons that we should open a bug up on github and
understand.  ***I would really like if that bug led to some documentation
about how we handle accessibility, and what we would like to see from
patchsets going forward in clear and concise rules***, and a patchset to
make the UI as it stands consistent in this regard.

**Comment by williamspatrick** [comment]
Can this be closed or moved?  @derick-montague

**Comment by derick-montague** [comment]
> Can this be closed or moved? @derick-montague

We can close this from my perspective. Thanks @williamspatrick.
