### ISSUE TITLE
OpenBMC Hello World in SDK

### ISSUE THREAD

**Issue by gchik** [openbmc/docs#48]
I'm newbie in OpenBMC. I started from the begining: https://github.com/openbmc/docs/tree/master/development and successfully made first step - Development Environment Setup. Now I'm trying to build Hello World in SDK (https://github.com/openbmc/docs/blob/master/development/sdk-hello-world.md).
When I use command:

./configure ${CONFIGURE_FLAGS}

I get  ERROR

...
checking for PHOSPHOR_DBUS_INTERFACES... no
configure: error: Package requirements (phosphor-dbus-interfaces) were not met:

No package 'phosphor-dbus-interfaces' found

What is this error means? What I need to do to fix it?

**Comment by geissonator** [comment]
I tried this over the weekend. I had a windows box, I installed Ubuntu 18, installed the pre-reqs into it and went through the doc process. It worked, but I did notice that the name of the SDK file has changed. I updated https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/25701 with this change.

**Comment by williamspatrick** [comment]
Closing as resolved.
