### ISSUE TITLE
Bitbake error:Nothing RPROVIDES'virtual=p9-vcs-workaround'

### ISSUE THREAD

**Issue by zzhuang-cancon** [openbmc/docs#51]
i am newbie in OpenBMC  and i follow this guidence : Add a New System to OpenBMC
everything is ok until i start to do building step : 
'bitbake obmc-phosphor-image'
and then i get 2 errors.
look below:
Parsing recipes: 100% |##################################################################################################################| Time: 0:03:28
Parsing of 2592 .bb files complete (0 cached, 2592 parsed). 3903 targets, 355 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'virtual-p9-vcs-workaround' (but /home/zhangzhuang/openbmc/meta-openpower/recipes-phosphor/host/p9-vcs-workaround.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'virtual-p9-vcs-workaround' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['virtual-p9-vcs-workaround']
NOTE: Runtime target 'p9-vcs-workaround' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['p9-vcs-workaround', 'virtual-p9-vcs-workaround']
NOTE: Runtime target 'virtual-obmc-host-ctl' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['virtual-obmc-host-ctl', 'p9-vcs-workaround', 'virtual-p9-vcs-workaround']
ERROR: Required build target 'obmc-phosphor-image' has no buildable providers.
Missing or unbuildable dependency chain was: ['obmc-phosphor-image', 'virtual-obmc-host-ctl', 'p9-vcs-workaround', 'virtual-p9-vcs-workaround']

i have do my best , try to find a solution to this problem, but it does not work.
if anyone give some suggestions?

**Comment by williamspatrick** [comment]
Are you trying to build a Power-based system?  The "p9 workaround" is for Power9 processors.

I would suggest posting to the mailing list with some more details about what machine / template config you are trying to build from.  You'll get more eyes on your questions from the mailing list.

https://lists.ozlabs.org/listinfo/openbmc

**Comment by solonfan** [comment]
Hi,zzhuang-cancon!

Have your error be fixed?I meet same error with yours.

Thanks,
SolonFan

**Comment by solonfan** [comment]
Hi,zzhuang-cancon!
I modified below file,and fix the build error[ERROR: Nothing RPROVIDES 'virtual-p9-vcs-workaround'],for your reference.

~/meta-romulus-prime/recipes-phosphor/host/p9-host-start.bbappend

Change RDEPENDS_${PN}_remove_romulus = "p9-vcs-workaround" to RDEPENDS_${PN}_remove_**romulus-prime** = "p9-vcs-workaround"

![Screenshot from 2020-06-11 15-52-34](https://user-images.githubusercontent.com/15608567/84359703-9b5e2200-abfb-11ea-841c-9c82775b5149.png)

Thanks,
SolonFan
