### ISSUE TITLE
Power monitoring and management didn't work

### ISSUE THREAD

**Issue by GarnetCrown** [openbmc/docs#52]
Hi, we use the Palmetto code,want to monitor the power status of the host and hard power on/off/cycle. We changed some pins, like PGOOD, RESET_BUTTON and POWER_BUTTON, but it didn't work. Can you give me some guidance for where should make changes, thank you very much.

**Comment by williamspatrick** [comment]
Please post support questions to the mailing list.  OpenBMC is a large project and not many people check the issues on the 'docs' repository, but most developers are subscribed to the mailing list.

https://lists.ozlabs.org/listinfo/openbmc

You'll need to describe the chains you made.  Are these software or hardware changes?
