### ISSUE TITLE
Not print hello word  

### ISSUE THREAD

**Issue by MR-Alex-Merfi** [openbmc/docs#56]
Hello !
not print hello word phosphor-bmc-state-manager
i follow the instruction  - https://github.com/openbmc/docs/blob/master/development/sdk-hello-world.md
root@romulus:~# /tmp/phosphor-bmc-state-manager 
^C
root@romulus:~# journalctl | tail
Nov 05 13:00:51 romulus systemd[1]: xyz.openbmc_project.State.BMC.service: Succeeded.
Nov 05 13:00:51 romulus systemd[1]: Stopped Phosphor BMC State Manager.
Nov 05 13:02:01 romulus systemd[1]: Created slice system-dropbear.slice.
Nov 05 13:02:01 romulus systemd[1]: Started SSH Per-Connection Server (10.0.2.2:53728).
Nov 05 13:02:01 romulus dropbear[321]: Child connection from ::ffff:10.0.2.2:53728
Nov 05 13:02:12 romulus dropbear[321]: PAM password auth succeeded for 'root' from ::ffff:10.0.2.2:53728
Nov 05 13:02:12 romulus dropbear[321]: Exit (root) from <::ffff:10.0.2.2:53728>: Disconnect received
Nov 05 13:02:12 romulus systemd[1]: dropbear@0-10.0.2.15:22-10.0.2.2:53728.service: Succeeded.
Nov 05 13:02:56 romulus phosphor-bmc-state-manager[327]: Setting the BMCState field
Nov 05 13:02:56 romulus phosphor-bmc-state-manager[327]: Setting the BMCState field

**Comment by geissonator** [comment]
Please provide the output as you do the different steps in the tutorial so we can help figure out where things went wrong.

**Comment by MR-Alex-Merfi** [comment]
create env (script created with install SDK) 
start romulus  - ./qemu-system-arm -m 256 -M romulus-bmc -nographic -drive file=./obmc-phosphor-image-romulus.static.mtd,format=raw,if=mtd -net nic -net user,hostfwd=:127.0.0.1:2222-:22,hostfwd=:127.0.0.1:2443-:443,hostname=qemu

1 [root@a Code]# git clone https://github.com/openbmc/phosphor-state-manager.git
Cloning into 'phosphor-state-manager'...
remote: Enumerating objects: 127, done.
remote: Counting objects: 100% (127/127), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 853 (delta 69), reused 99 (delta 41), pack-reused 726
Receiving objects: 100% (853/853), 293.59 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (524/524), done.

2 cd phosphor-state-manager
vi bmc_state_manager_main.cpp

#include <iostream>
..........................
bus.request_name(BMC_BUSNAME);

    std::cout<<"Hello World" <<std::endl;

    while (true)

3 meson build - not error
................................
Found ninja-1.10.1 at /root/sdk/romulus-2020-11-03/sysroots/x86_64-oesdk-linux/usr/bin/ninja

ninja -C build - not error
.............many string build........and 
/root/sdk/romulus-2020-11-03/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/include/c++/10.2.0/bits/stl_uninitialized.h:84:9: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<const nlohmann::basic_json<>*, std::vector<nlohmann::basic_json<>, std::allocator<nlohmann::basic_json<> > > >’ changed in GCC 7.1
[33/33] Linking target test_scheduled_host_transition

**build finished without problems**
 Load application in qemu
[root@a phosphor-state-manager]# arm-openbmc-linux-gnueabi-strip /root/sdk/romulus-2020-11-03/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/bin/phosphor-bmc-state-manager

Create directory in romulus for overlay
root@romulus:~# mkdir -p /tmp/persist/usr
root@romulus:~# mkdir -p /tmp/persist/work/usr
root@romulus:~# mount -t overlay -o lowerdir=/usr,upperdir=/tmp/persist/usr,workdir=/tmp/persist/work/usr overlay /usr
[  929.301097] overlayfs: upper fs does not support xattr, falling back to index=off and metacopy=off.

[root@a phosphor-state-manager]# scp -P 2222 /root/sdk/romulus-2020-11-03/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/bin/phosphor-bmc-state-manager root@127.0.0.1:/usr/bin/
root@127.0.0.1's password: 
phosphor-bmc-state-manager                                                                                          100%   34KB   2.8MB/s   00:00    

root@romulus:~# systemctl stop xyz.openbmc_project.State.BMC.service
root@romulus:~# phosphor-bmc-state-manager -  not print Hello Word 

^C
root@romulus:~# journalctl | tail
Nov 06 08:14:11 romulus systemd[1]: Started SSH Per-Connection Server (10.0.2.2:53802).
Nov 06 08:14:11 romulus dropbear[325]: Child connection from ::ffff:10.0.2.2:53802
Nov 06 08:14:16 romulus dropbear[325]: PAM password auth succeeded for 'root' from ::ffff:10.0.2.2:53802
Nov 06 08:14:16 romulus dropbear[325]: Exit (root) from <::ffff:10.0.2.2:53802>: Disconnect received
Nov 06 08:14:16 romulus systemd[1]: dropbear@0-10.0.2.15:22-10.0.2.2:53802.service: Succeeded.
Nov 06 08:15:09 romulus systemd[1]: Stopping Phosphor BMC State Manager...
Nov 06 08:15:09 romulus systemd[1]: xyz.openbmc_project.State.BMC.service: Succeeded.
Nov 06 08:15:09 romulus systemd[1]: Stopped Phosphor BMC State Manager.
Nov 06 08:15:54 romulus phosphor-bmc-state-manager[336]: Setting the BMCState field
Nov 06 08:15:54 romulus phosphor-bmc-state-manager[336]: Setting the BMCState field

**Comment by MR-Alex-Merfi** [comment]
this case is close .
