### ISSUE TITLE
Missing a step in documentation

### ISSUE THREAD

**Issue by viggy96** [openbmc/docs#68]
I've been following the "Adding a new system" document here: https://github.com/openbmc/docs/blob/master/development/add-new-system.md

And I get to the step that says: `Nothing RPROVIDES 'romulus-prime-config'`
First of all, I don't get that error, instead I get:
`ERROR: BBFILE_PATTERN_romulus-prime-layer not defined`
Also, following that, the instructions say to copy some files:
`cp meta-ibm/meta-romulus-prime/recipes-phosphor/workbook/romulus-config.bb meta-ibm/meta-romulus-prime/recipes-phosphor/workbook/romulus-prime-config.bb`

However, I don't see the "workbook" directory.
```
ls meta-ibm/meta-romulus-prime/recipes-phosphor/    
chassis        console  flash  host    inventory  leds     mboxd  packagegroups  skeleton
configuration  fans     gpio   images  ipmi       logging  occ    sensors        state
```
I'm confused as to what to do here.

**Comment by williamspatrick** [comment]
@geissonator Can you recommend someone to update this?  Looks like you made the original version and it hasn't really been updated since 2018.

**Comment by geissonator** [comment]
Yeah, I'll queue it up, may be a bit. I wonder if there's a better example now a days, or if there's really much value in this "copy-an-existing-config-and-tweak-it" type tutorial. Creating a new machine from scratch is a bit outside of the scope of a tutorial. Maybe tweak it to be more like this is how you'd make a derivative machine under an existing layer.

**Comment by williamspatrick** [comment]
> Creating a new machine from scratch is a bit outside of the scope of a tutorial.

@geissonator Should we remove the "tutorial"?

**Comment by geissonator** [comment]
Yeah, I'm not going to have time to do much here. I know there's a desire for a document on all the pieces to adding a new  system but that should be outside of a tutorial. So yeah, I think we should just remove add-new-system.md, I'll put up a gerrit commit.

**Comment by geissonator** [comment]
https://gerrit.openbmc-project.xyz/c/openbmc/docs/+/49144

**Comment by gluhow** [comment]
I am a beginner at OpenBmc. This material was very useful to me. I also tried to copy and rename Romulus and only with the help of the tutorial I was able to understand my mistakes.
I am currently making a minimal image https://github.com/gluhow/openbmc/tree/minimum (meta-sample/meta-ast2500-min). It is possible that it will be useful too.
