### ISSUE TITLE
In phosphor-webui,How can I connect 8080 with 2443(backend)

### ISSUE THREAD

**Issue by fishermess** [openbmc/docs#69]
After bitbake and runing image,I got chance to visit "http://localhost:8080".However,I can;t login in from 8080 to 2443,beacuse 8080 is http and 2443 is https.They are in different region!
Who can tell me what I can do?

**Comment by gtmills** [comment]
First I should warn, a lot of users are moving away from phosphor-webui to webui-vue. 
https://github.com/openbmc/webui-vue#should-i-switch-to-webui-vue-from-phosphor-webui 

webui-vue uses Redfish, while phoshor-webui uses the REST D-BUS API which we plan to turn off as default in bmcweb here soon. phosphor-webui also uses AngularJS which is end of life. 

So based on ""http://localhost:8080", you must be running the GUI locally? npm run-script server ?
This conflicts with your statement about bitbake and running image.. Can you explain your setup more? 

If running locally, after browsing to http://localhost:8080, you should be able to enter the BMC IP address/hostname. 

If you instead, built an image that included phosphor-webui or webui-vue after code updating to that image, just browse to https://<bmc IP address or hostname>

**Comment by williamspatrick** [comment]
Opening issues to openbmc/docs is not the best way to get support.  Please use the mailing list or Discord.
