### ISSUE TITLE
BMC state not ready after add a new system

### ISSUE THREAD

**Issue by t108368069** [openbmc/docs#70]
Hi, I followed the steps in this [tutorial](https://github.com/openbmc/docs/blob/master/development/add-new-system.md#add-a-new-system-to-openbmc).
I started QEMU with the `romulus-prime` image, the `obmcutil state` command showed these:
```
root@romulus-prime:~# obmcutil state
CurrentBMCState     : xyz.openbmc_project.State.BMC.BMCState.NotReady
CurrentPowerState   : xyz.openbmc_project.State.Chassis.PowerState.Off
CurrentHostState    : xyz.openbmc_project.State.Host.HostState.Off
BootProgress        : xyz.openbmc_project.State.Boot.Progress.ProgressStages.Unspecified
OperatingSystemState: xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.Inactive
``` 
The original `romulus` build works fine, but if I use the `romulus-prime` build that modified `conf` files as the tutorial said, I got BMC state not ready.
I know the tutorial is kind of outdated, but I'm not sure if I made some mistakes.
Lastly, if `journalctl` output or other details are helpful, please let me know.

Thanks!
Victor.

**Comment by t108368069** [comment]
**Update:**
The BMC state turns to ready after executing `obmcutil poweron` and `obmcutil poweroff` .

**Comment by williamspatrick** [comment]
If the bmc isn't `Ready` that usually means that systemd hasn't reached the appropriate target.  `systemctl list-jobs` is usually helpful to debug this.

Please don't open issues to openbmc/docs for support.  You should get more response out of the mailing list and/or Discord.
