### ISSUE TITLE
openbmc,Hwmon Sensors, Fan diaplay web problem

### ISSUE THREAD

**Issue by cld795** [openbmc/docs#71]
Hi,

I have a problem  need your help,
And
I set it  like this:
![image](https://user-images.githubusercontent.com/90960508/141443334-23318040-68c0-45dd-a7bd-38bab039c0c9.png)
![image](https://user-images.githubusercontent.com/90960508/141443357-c8e50332-49a2-43a6-982f-90a7ea5d65a6.png)
![image](https://user-images.githubusercontent.com/90960508/141443379-263c141b-ca2a-46ef-a400-d91acdc715d5.png)
![image](https://user-images.githubusercontent.com/90960508/141443393-62503938-3b67-4a9d-a60c-62db482bed3f.png)
Linux has achieved the normal control of PWM Fan:
![image](https://user-images.githubusercontent.com/90960508/141443415-fae6bfd6-20ed-44c4-b80f-aa6eaa0a802f.png)
use ipmitool sensor can display the fan information:
![image](https://user-images.githubusercontent.com/90960508/141443431-886391de-47c3-4ae1-8124-1ff7dcfea4b6.png)
but web Unable to display the fan:
![image](https://user-images.githubusercontent.com/90960508/141443450-b43d7360-08cb-442c-80f4-a3f97e6e071f.png)
so need your give me some guidance,Thank you very much!

Thanks.

Best Regards

**Comment by williamspatrick** [comment]
This is not the appropriate place to ask for support on OpenBMC overall...  Please use the mailing list or Discord.
