### ISSUE TITLE
Example command to get latest Romulus image isn't working

### ISSUE THREAD

**Issue by RobPellowski** [openbmc/docs#73]
## Location
development tutorials...OpenBMC Developer Documentation...Development Environment Setup...Download and Start QEMU Session...Download the Romulus image

## Issue
This command
`wget https://jenkins.openbmc.org/job/latest-master/label=docker-builder,target=romulus/lastSuccessfulBuild/artifact/openbmc/build/tmp/deploy/images/romulus/obmc-phosphor-image-romulus.static.mtd`
returns
`2022-03-29 09:54:25 ERROR 404: Not Found`
Actual filename has the format
`obmc-phosphor-image-romulus-20220329025139.static.mtd`

## Request
Provide a working example using `wget` for those who are not familiar with the Jenkins api

**Comment by williamspatrick** [comment]
@geissonator Do we have something misconfigured on Jenkins?  When I go to the `tmp/deploy/images/romulus` directory I see:

>  Symlinks are hidden

**Comment by williamspatrick** [comment]
@geissonator Also if I download the .zip archive it does not contain the `obmc-phosphor-image-romulus.static.mtd` symlink either.

**Comment by geissonator** [comment]
Unfortunately, Jenkins disabled showing links in artifacts due to security concerns. They provided no way to disable this. My workaround has been to manually copy the linked to file to the link name for specific images CI needs. I'll add this workaround to the latest-master job.

**Comment by RobPellowski** [comment]
Working as expected, thanks!
