### ISSUE TITLE
Hello world example is failed in ninja -C build

### ISSUE THREAD

**Issue by gixttl** [openbmc/docs#77]
Hi,

I'm tying to follow Hello world example to familier to the openbmc.
I met the problems which are described and resolved earlier post and solved it.
But, there is an another problem.
Could you give me some guide to resolve those link errror below?

### - Relevant Info:
Operating system: Ubuntu 20.04.4 LTS (Focal)
Branch/Commit: phosphor-state-manager/main ("master") 7e0e4e9227d495b47ebc6c38b97998254dcad5be

### - Problem:
  Description: link error in the header file "sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/include/fmt/core.h".
  Log: (Sorry. I can't upload full log due to restrictions in my work space.)
ninja: Entering directory `build'
[1/4] Linking target test_hypervisor_state
[2/4] Linking target test_scheduled_host_transition
[3/4] Linking target phosphor-secure-boot-check
FAILED: phosphor-secure-boot-check 
arm-openbmc-linux-gnueabi-g++ -marm -mcpu=arm1176jz-s -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi  -o phosphor-secure-boot-check phosphor-secure-boot-check.p/secure_boot_check.cpp.o phosphor-secure-boot-check.p/utils.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-z,relro,-z,now -Wl,--start-group /home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/lib/libsdbusplus.so /home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/lib/libsystemd.so /home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/lib/libphosphor_logging.so /home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/lib/libphosphor_dbus.so /home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/lib/libgpiod.so -Wl,--end-group
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/x86_64-oesdk-linux/usr/libexec/arm-openbmc-linux-gnueabi/gcc/arm-openbmc-linux-gnueabi/12.1.0/real-ld: phosphor-secure-boot-check.p/utils.cpp.o: in function `std::make_unsigned<int>::type fmt::v8::detail::to_unsigned<int>(int)':
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/include/fmt/core.h:426: undefined reference to `fmt::v8::detail::assert_fail(char const*, int, char const*)'
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/x86_64-oesdk-linux/usr/libexec/arm-openbmc-linux-gnueabi/gcc/arm-openbmc-linux-gnueabi/12.1.0/real-ld: phosphor-secure-boot-check.p/utils.cpp.o: in function `fmt::v8::detail::format_decimal_result<char*> fmt::v8::detail::format_decimal<char, unsigned long long>(char*, unsigned long long, int)':
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/include/fmt/format.h:1108: undefined reference to `fmt::v8::detail::assert_fail(char const*, int, char const*)'
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/x86_64-oesdk-linux/usr/libexec/arm-openbmc-linux-gnueabi/gcc/arm-openbmc-linux-gnueabi/12.1.0/real-ld: phosphor-secure-boot-check.p/utils.cpp.o: in function `unsigned int fmt::v8::detail::printf_width_handler<char>::operator()<fmt::v8::monostate, 0>(fmt::v8::monostate)':
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/include/fmt/printf.h:219: undefined reference to `vtable for fmt::v8::format_error'
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/x86_64-oesdk-linux/usr/libexec/arm-openbmc-linux-gnueabi/gcc/arm-openbmc-linux-gnueabi/12.1.0/real-ld: /home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/include/fmt/printf.h:219: undefined reference to `fmt::v8::format_error::~format_error()'
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/x86_64-oesdk-linux/usr/libexec/arm-openbmc-linux-gnueabi/gcc/arm-openbmc-linux-gnueabi/12.1.0/real-ld: /home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/include/fmt/printf.h:219: undefined reference to `typeinfo for fmt::v8::format_error'
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/x86_64-oesdk-linux/usr/libexec/arm-openbmc-linux-gnueabi/gcc/arm-openbmc-linux-gnueabi/12.1.0/real-ld: phosphor-secure-boot-check.p/utils.cpp.o: in function `int fmt::v8::detail::printf_precision_handler::operator()<fmt::v8::monostate, 0>(fmt::v8::monostate)':
/home/gt82lee/project/bmc/sdk/romulus-2022-09-02/sysroots/arm1176jzs-openbmc-linux-gnueabi/usr/include/fmt/printf.h:91: undefined reference to `vtable for fmt::v8::format_error'

**Comment by williamspatrick** [comment]
Documentation has been updated to no longer suggest use of the SDK.

**Comment by gixttl** [comment]
@williamspatrick Thanks for the update :)
