### ISSUE TITLE
Question about OpenBMC -> Board integration

### ISSUE THREAD

**Issue by jorgeventura** [openbmc/docs#84]
What documentation I should use to learn how to integrate OpenBMC to host motherboard ?
Most of the documents seems to be about OpenBMC embedded in new MC hardware. Am I wrong?

Sincerely,
Jorge Ventura

PS: I am posting here because I don't know where to do that and I apologize if it's the wrong place.

**Comment by williamspatrick** [comment]
I don't understand what you are asking.  Maybe you're looking for this?  https://github.com/openbmc/docs/blob/master/development/add-new-system.md

That document probably isn't 100% up to date but it is a decent starting point.  After that the suggestion tends to be to look at existing machines in https://github.com/openbmc/openbmc and try to match up your requirements with one of those reference implementations.  Feel free to join the Discord community to ask more specific questions if you start on an effort to port OpenBMC to your machine.
